# Generated by Django 4.2.1 on 2023-07-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Etiqueta',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='tag',
            new_name='etiqueta',
        ),
    ]
