# Generated by Django 4.2.1 on 2023-07-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_tag_etiqueta_rename_tag_tarea_etiqueta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='usuario',
            new_name='user',
        ),
    ]
