# Generated by Django 4.2.1 on 2023-07-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_tarea_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('En progreso', 'en_progreso'), ('Completada', 'completada')], default='pendiente', max_length=20),
        ),
    ]
