# Generated by Django 4.2.1 on 2023-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
